site_name: Toolsmith
theme:
  name: material

nav:
  - Home: index.md
  - API Reference: reference.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            inherited_members: true
